
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";
export const FETCH_LATEST_ENROLLMENT_COLUMN_SUCCESS = "FETCH_LATEST_ENROLLMENT_COLUMN_SUCCESS";
export const FETCH_LATEST_ENROLLMENT_COLUMN_FAILURE = "FETCH_LATEST_ENROLLMENT_COLUMN_FAILURE";
export const FETCH_LATEST_ENROLLMENT_DATA_SUCCESS = "FETCH_LATEST_ENROLLMENT_DATA_SUCCESS";
export const FETCH_LATEST_ENROLLMENT_DATA_FAILURE = "FETCH_LATEST_ENROLLMENT_DATA_FAILURE";
export const FETCH_BEST_ENROLLMENT_COLUMN_SUCCESS = "FETCH_BEST_ENROLLMENT_COLUMN_SUCCESS";
export const FETCH_BEST_ENROLLMENT_COLUMN_FAILURE = "FETCH_BEST_ENROLLMENT_COLUMN_FAILURE";
export const FETCH_BEST_ENROLLMENT_DATA_SUCCESS = "FETCH_BEST_ENROLLMENT_DATA_SUCCESS";
export const FETCH_BEST_ENROLLMENT_DATA_FAILURE = "FETCH_BEST_ENROLLMENT_DATA_FAILURE";


// ActionType/loginActionTypes.js

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
